# This file was generated by GoReleaser. DO NOT EDIT.
cask "packc" do
  version "1.5.9"

  on_macos do
    on_intel do
      sha256 "bda8ad26a2b59540a319fc28e096ecb640eda55b6027aa56147971d899dc8512"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "547b8e01f16031e36051ba4849db8115d44affb30d9b0124b20031891a99b401"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e2fae6fcdb6bc18ffa3246a837e04a66327315c8444f2b5fc072c79bd81c715b"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "28c3561fd81a5f06c2f43c060832a667e02677211819da1b4349bfc7815a0195"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "packc"
  desc "packc — PromptArena pack compiler"
  homepage "https://github.com/AltairaLabs/promptarena"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "packc"

  # No zap stanza required

end
