# This file was generated by GoReleaser. DO NOT EDIT.
cask "packc" do
  version "1.6.5"

  on_macos do
    on_arm do
      sha256 "603526630485c50e5b78eded8d40d437935bbef8185c2ac99461e5d17ca61c40"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0bf7f05e617a02d29aba969c03456d0bb30ba93adf7c4e8edf17e17337d8d17f"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a958100a485585fd0653ab4a438405b424111973b08d0453f369658c25d0a7f5"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "86572abddab99613b4481b6f0796a14759a2b7265445856791fe2ed09ec05be5"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "packc"
  desc "packc — PromptArena pack compiler"
  homepage "https://github.com/AltairaLabs/promptarena"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "packc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/packc"],
                     sudo: false
    end
  end

  # No zap stanza required
end
