# This file was generated by GoReleaser. DO NOT EDIT.
cask "packc" do
  version "1.5.5"

  on_macos do
    on_intel do
      sha256 "7d720df30cc9b885d806ede6a241213feff1a32b8b485675ac0340f5efed9e91"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7d4253e3cdcebe01022867d75a1ad2dff97ccea9abdfc1ac4e802644c1fb4795"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "341ad83b5a9168d8345c56d53f69d80f76c07ab39869147dafd9d31b8568bb3e"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3fa7b61ba28f622ce6aec4af7bb91a022fc27a472a9f4774faa468f6140a8a49"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/packc_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "packc"
  desc "packc — PromptArena pack compiler"
  homepage "https://github.com/AltairaLabs/promptarena"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "packc"

  # No zap stanza required

end
