# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptarena" do
  version "1.5.5"

  on_macos do
    on_intel do
      sha256 "bc7fa0223c711ae2f2cbac901938d31529f17f44a0653b07fdc5267ee8447a6f"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "41332f795ef71e5c3b561be5b2d35f77a448e28d394372b1247b27756ef6abfa"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b389b6a7a37a855ea761e309441bc20c50c95d1a0a8e1311effcfaa7a8cb5ae"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f1065d093ac2334066db07eeb9b3a399d14a539772a82919df402c0cf1f8ecfb"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "promptarena"
  desc "PromptArena — prompt testing and evaluation CLI"
  homepage "https://github.com/AltairaLabs/promptarena"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promptarena"

  # No zap stanza required

end
