# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptarena" do
  version "1.6.1"

  on_macos do
    on_arm do
      sha256 "667c84b667a7e9860322f0ca45a9246e45eb788bce6acb85b2dd68d29d682254"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "930e721b06da2a550203d3ac2d18817d64c38102070ee0164800fb7218a41456"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1f773c2260c5d8f96626ff5a9a4c509c6f5105f1a4fd7509448faffa784aaa8c"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "487ecbcf5780386a6c1d090e3774abdb1a346857938b9fbda085c4ca7b65a0e6"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "promptarena"
  desc "PromptArena — prompt testing and evaluation CLI"
  homepage "https://github.com/AltairaLabs/promptarena"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promptarena"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/promptarena"],
                     sudo: false
    end
  end

  # No zap stanza required
end
