# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptkit" do
  name "promptkit"
  desc "Prompt testing and evaluation toolkit for AI applications"
  homepage "https://github.com/AltairaLabs/PromptKit"
  version "1.3.23"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promptarena"
  binary "packc"

  on_macos do
    on_intel do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Darwin_x86_64.tar.gz"
      sha256 "6b871d6cdccd2f806c929822c10d5ec795cc696d506db168a1f7d8aafdd71226"
    end
    on_arm do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Darwin_arm64.tar.gz"
      sha256 "b0ffe9f31511ba27745ceb6c3b08e9b046cccf64059663dff784673d066f674f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Linux_x86_64.tar.gz"
      sha256 "8d99fa7613f4f4a4b40548a71a80bd15ae784339f82f3a19032f44eb24e7cbe0"
    end
    on_arm do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Linux_arm64.tar.gz"
      sha256 "a782a346b4ffad49e0c55053e01d43116d7e7e9267a4c82be4dc627b44973a2e"
    end
  end

  # No zap stanza required
end
