# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptkit" do
  version "1.4.6"

  on_macos do
    on_intel do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Darwin_x86_64.tar.gz"
      sha256 "1ac05f0ce5d83a684a9502bb4dc7986f27660e98f9667af650561ac899b7844a"
    end
    on_arm do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Darwin_arm64.tar.gz"
      sha256 "2b004417f80f23e778106cbb6fc3e44c48e535cc8a9a285418b48cb34638f716"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Linux_x86_64.tar.gz"
      sha256 "b4c1072398a17eeb95a37607648256ff4ba2810bf1200d41616411a62f5dd1bd"
    end
    on_arm do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Linux_arm64.tar.gz"
      sha256 "62089eeef81d4f328bf50b72d58f61181aaa57fe3cd0a8bded5696553cc354a9"
    end
  end

  name "promptkit"
  desc "Prompt testing and evaluation toolkit for AI applications"
  homepage "https://github.com/AltairaLabs/PromptKit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promptarena"
  binary "packc"

  # No zap stanza required

end
