# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptkit" do
  name "promptkit"
  desc "Prompt testing and evaluation toolkit for AI applications"
  homepage "https://github.com/AltairaLabs/PromptKit"
  version "1.3.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promptarena"
  binary "packc"

  on_macos do
    on_intel do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Darwin_x86_64.tar.gz"
      sha256 "dbc0e4716bb52d7b10daf2f3b7ff0f02a219e2daf4d06c79ae613eff5ea83e61"
    end
    on_arm do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Darwin_arm64.tar.gz"
      sha256 "30ad023e0845df3b7188bced745407f42e37475203f59e3e2734c47239dd3521"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Linux_x86_64.tar.gz"
      sha256 "7a7edcebc9e52057c878a6e7e667049a7db46f2f90f82aa3c7d80858136d24d1"
    end
    on_arm do
      url "https://github.com/AltairaLabs/PromptKit/releases/download/v#{version}/PromptKit_#{version}_Linux_arm64.tar.gz"
      sha256 "9f1686fd5457a995a02945ad48b3ff374e50c7ab96fc6bba7937255ff2d8bcd5"
    end
  end

  # No zap stanza required
end
