# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptarena" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "b7c5caf96a27723939fb8034e46f4812a0ae9b59716bf43dcb6d36757b34e0a4"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "315aeb58b59f32ae6575ae27c84afa83e0496c621de82bfc9cb71e87ccb94970"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0d194cb8880b2df0a10beff3b2db92ecb19c40fa133086d12aa59969bfa5a294"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "67482d0def57139806851d0b393793fbadd5766a7efaa3f9ebfc60efffc59d5d"
      url "https://github.com/AltairaLabs/promptarena/releases/download/v#{version}/promptarena_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "promptarena"
  desc "PromptArena — prompt testing and evaluation CLI"
  homepage "https://github.com/AltairaLabs/promptarena"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promptarena"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/promptarena"],
                     sudo: false
    end
  end

  # No zap stanza required
end
